### PR TITLE
Streams order, use format: "set" for streams

### LINKED ISSUE #83: Streams order changed between terraform plan and apply
👋🏻 Hello

I am seing a strange behaviour in the terraform provider. A connection which is not updated will appear in the state (`terraform plan`) as modified because the streams list order can change over time.

This is problematic because we discard fields we don't want to synchronize to our destination but when terraform applies the change on the connection, it will reset the fields selection, which is far from ideal.

Is there a way to ensure consistency of streams order ?

### PR DESCRIPTION
**Pull request by szemek**
Fixes #83

### CODE REVIEW

**Comment by lucasmazza** [comment]
We tested this diff on our setup (following the `Testing the provider locally` instructions on the README) and it fixes the noisy plan diffs we get on connections with a lot of streams. Thanks so much for the patch.

What else do we need to get this merged and released?

**Comment by dholleran-volt** [comment]
@JonsSpaghetti @bgroff could you guys have a look when you get a chance?

**Comment by szemek** [comment]
@lucasmazza @dholleran-volt I'm in touch with Airbyte team. I got info from @marcosmarxm that @perangel will be back on July 15th from his PTO and he'll take care of it.

**Comment by perangel** [comment]
I have PR up https://github.com/airbytehq/terraform-provider-airbyte/pull/128 with the proposed changes. There is a link to the branch that has the fully generated provider source that you can use to run it locally to verify if it fixes your use case

**Comment by szemek** [comment]
[#128](https://github.com/airbytehq/terraform-provider-airbyte/pull/128) fixed https://github.com/airbytehq/terraform-provider-airbyte/issues/83. I'm closing this pull request.

**Pull request closed without merging**
